# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Adf2md < Formula
  desc "A Go command-line tool to convert Atlassian Document Format (ADF) JSON into Markdown."
  homepage ""
  version "0.1.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/carylee/adf2md/releases/download/v0.1.5/adf2md_Darwin_x86_64.tar.gz"
      sha256 "8f298b3fe36ecb8224558e005100b945117bc517ebe96c114e0f38167b2add72"

      def install
        bin.install "adf2md"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/carylee/adf2md/releases/download/v0.1.5/adf2md_Darwin_arm64.tar.gz"
      sha256 "cf2020ccc32bddbf9f811f61ba45f465de306e89cb16acb10e2172254b462f97"

      def install
        bin.install "adf2md"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/carylee/adf2md/releases/download/v0.1.5/adf2md_Linux_x86_64.tar.gz"
      sha256 "67f5bca38d9d4cc85b0d0867cbd9b70ca874644855bb0dd494e1bd19207daa32"
      def install
        bin.install "adf2md"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/carylee/adf2md/releases/download/v0.1.5/adf2md_Linux_arm64.tar.gz"
      sha256 "dca81cf113fa59cafbc4b3f5e2b2fa00cf3cc29b97fce1908db0e7be56dcc2e7"
      def install
        bin.install "adf2md"
      end
    end
  end

  test do
    system "#{bin}/adf2md --version"
  end
end
